ALTER TABLE jobs ADD COLUMN projectRevision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE jobs ADD COLUMN workflowId TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN pid INTEGER;
ALTER TABLE jobs ADD COLUMN acceptedAt TEXT;
ALTER TABLE jobs ADD COLUMN errorMessage TEXT;
ALTER TABLE jobs ADD COLUMN stopMode TEXT;

ALTER TABLE jobEvents ADD COLUMN sequence INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobEvents ADD COLUMN projectId TEXT NOT NULL DEFAULT '';
ALTER TABLE jobEvents ADD COLUMN workflowId TEXT NOT NULL DEFAULT '';
ALTER TABLE jobEvents ADD COLUMN workflowRunId TEXT NOT NULL DEFAULT '';
ALTER TABLE jobEvents ADD COLUMN parentWorkflowRunId TEXT NOT NULL DEFAULT '';
ALTER TABLE jobEvents ADD COLUMN nodeRunId TEXT NOT NULL DEFAULT '';
ALTER TABLE jobEvents ADD COLUMN iterationPathJson TEXT NOT NULL DEFAULT '[]';
ALTER TABLE jobEvents ADD COLUMN timestampMs INTEGER NOT NULL DEFAULT 0;

UPDATE jobEvents SET sequence = eventId WHERE sequence = 0;
CREATE UNIQUE INDEX IF NOT EXISTS idx_jobEvents_job_sequence ON jobEvents(jobId, sequence);
CREATE TABLE IF NOT EXISTS schemaMigrations (
  version INTEGER PRIMARY KEY,
  appliedAt TEXT NOT NULL
);
