from enum import Enum


class ErrorCode(str, Enum):
  E_PARAM_INVALID = "E_PARAM_INVALID"
  E_INPUT_MISSING = "E_INPUT_MISSING"
  E_INPUT_TYPE = "E_INPUT_TYPE"
  E_INPUT_SHAPE = "E_INPUT_SHAPE"
  E_EXEC_FAILED = "E_EXEC_FAILED"
  E_OPERATOR_UNAVAILABLE = "E_OPERATOR_UNAVAILABLE"
