from enum import Enum


class ErrorCode(str, Enum):
  E_PARAM_INVALID = "E_PARAM_INVALID"
  E_INPUT_MISSING = "E_INPUT_MISSING"
  E_INPUT_TYPE = "E_INPUT_TYPE"
  E_INPUT_SHAPE = "E_INPUT_SHAPE"
  E_EXEC_FAILED = "E_EXEC_FAILED"
  E_OPERATOR_UNAVAILABLE = "E_OPERATOR_UNAVAILABLE"
  E_WORKFLOW_INVALID = "E_WORKFLOW_INVALID"
  E_WORKFLOW_RECURSIVE = "E_WORKFLOW_RECURSIVE"
  E_CALL_DEPTH = "E_CALL_DEPTH"
  E_CANCELLED = "E_CANCELLED"
  E_LOOP_LIMIT_REACHED = "E_LOOP_LIMIT_REACHED"
  E_LOOP_TIMEOUT = "E_LOOP_TIMEOUT"
  E_JOB_NOT_FOUND = "E_JOB_NOT_FOUND"
  E_RUNTIME_RESTARTED = "E_RUNTIME_RESTARTED"
  E_WORKER_CRASHED = "E_WORKER_CRASHED"
